# Carla topics and params
hd_map: "Town10HD_Opt"
target_fps: 60.0 # This is for the client in synch mode.
carla_info_topic: "carla_simulation_info"
carla_actor_id_topic: "carla_actor_id"
quit_simulation_topic: "quit_simulation"

# Vehicle control commands
vehicle_cmd_topic: "carla_vehicle_cmd"
vehicle_control_topic: "vehicle_control"
ackermann_cmd_topic: "ackermann_cmd"
ackermann_joy_topic: "ackermann_joy"

# Vehicle physical params
vehicle_lf: 1.42

# Localization topics and params
selected_odometry_topic: "filtered_odometry_front"
filtered_odometry_topic: "filtered_odometry"
wheel_odometry_topic: "wheel_odometry"
wheel_distance_topic: "wheel_distance"
gps_topic: "gps/fix"
gps_local_odometry_topic: "gps_local_odometry"
geo_projection: "+proj=tmerc +lat_0=40.354550084445 +lon_0=-3.7463664011244586 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs"

# Tf transformation tree frames
map_frame: "map"
footprint_frame: "ego/base_footprint"
odom_frame: "ego/odom"
front_wheel_frame: "ego/front_wheel_axis"
wheel_joint_names: [
  "ego_front_right_wheel_steer_joint", "ego_front_right_wheel_joint",
  "ego_front_left_wheel_steer_joint", "ego_front_left_wheel_joint",
  "ego_back_right_wheel_joint", "ego_back_left_wheel_joint"
]

# /**: will set the parameter string_param on all nodes,
# /**/some_node: will set the parameter string_param on nodes named some_node in any namespace,
# /foo/*: will set the parameter string_param on any node in the namespace /foo.
